// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q72kFJDPbi6GCvfvYJFAr
// Component: fpXbpiSnmBO-
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: q72kFJDPbi6GCvfvYJFAr/projectcss
import sty from "./PlasmicFooterBottomHalcyon.module.css"; // plasmic-import: fpXbpiSnmBO-/css

createPlasmicElementProxy;

export const PlasmicFooterBottomHalcyon__VariantProps = new Array();

export const PlasmicFooterBottomHalcyon__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooterBottomHalcyon__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"footerBottom"}
        data-plasmic-override={overrides.footerBottom}
        className={classNames(projectcss.all, sty.footerBottom)}
      >
        <div
          data-plasmic-name={"container2"}
          data-plasmic-override={overrides.container2}
          className={classNames(projectcss.all, sty.container2)}
        >
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {"\u00a9 HalcyonStudios. All rights reserved."}
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "footerBottom", "container2", "text"],
  footerBottom: ["footerBottom", "container2", "text"],
  container2: ["container2", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooterBottomHalcyon__ArgProps,
          internalVariantPropNames: PlasmicFooterBottomHalcyon__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooterBottomHalcyon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterBottomHalcyon";
  } else {
    func.displayName = `PlasmicFooterBottomHalcyon.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterBottomHalcyon = Object.assign(
  // Top-level PlasmicFooterBottomHalcyon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    footerBottom: makeNodeComponent("footerBottom"),
    container2: makeNodeComponent("container2"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicFooterBottomHalcyon
    internalVariantProps: PlasmicFooterBottomHalcyon__VariantProps,
    internalArgProps: PlasmicFooterBottomHalcyon__ArgProps
  }
);

export default PlasmicFooterBottomHalcyon;
/* prettier-ignore-end */
