// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q72kFJDPbi6GCvfvYJFAr
// Component: 27UV0xTioSRX
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import HalcyonNavBar from "../../HalcyonNavBar"; // plasmic-import: BJ5uREdrA1yX/component
import BannerPolicies from "../../BannerPolicies"; // plasmic-import: oNYs1kJmnTzr/component
import ContainerTermsOfService from "../../ContainerTermsOfService"; // plasmic-import: WW8SK_BcqV2e/component
import FooterHalcyon from "../../FooterHalcyon"; // plasmic-import: bbtps6nNPDXa/component
import FooterBottomHalcyon from "../../FooterBottomHalcyon"; // plasmic-import: fpXbpiSnmBO-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: q72kFJDPbi6GCvfvYJFAr/projectcss
import sty from "./PlasmicTermsOfService.module.css"; // plasmic-import: 27UV0xTioSRX/css

createPlasmicElementProxy;

export const PlasmicTermsOfService__VariantProps = new Array();

export const PlasmicTermsOfService__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTermsOfService__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <HalcyonNavBar
            data-plasmic-name={"halcyonNavBar"}
            data-plasmic-override={overrides.halcyonNavBar}
            className={classNames("__wab_instance", sty.halcyonNavBar)}
          />

          <BannerPolicies
            data-plasmic-name={"bannerPolicies"}
            data-plasmic-override={overrides.bannerPolicies}
            className={classNames("__wab_instance", sty.bannerPolicies)}
            unnamedVariant2={true}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <ContainerTermsOfService
              data-plasmic-name={"containerTermsOfService"}
              data-plasmic-override={overrides.containerTermsOfService}
              className={classNames(
                "__wab_instance",
                sty.containerTermsOfService
              )}
            />
          </section>
          <FooterHalcyon
            data-plasmic-name={"footerHalcyon"}
            data-plasmic-override={overrides.footerHalcyon}
            className={classNames("__wab_instance", sty.footerHalcyon)}
          />

          <FooterBottomHalcyon
            data-plasmic-name={"footerBottomHalcyon"}
            data-plasmic-override={overrides.footerBottomHalcyon}
            className={classNames("__wab_instance", sty.footerBottomHalcyon)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "halcyonNavBar",
    "bannerPolicies",
    "section",
    "containerTermsOfService",
    "footerHalcyon",
    "footerBottomHalcyon"
  ],

  halcyonNavBar: ["halcyonNavBar"],
  bannerPolicies: ["bannerPolicies"],
  section: ["section", "containerTermsOfService"],
  containerTermsOfService: ["containerTermsOfService"],
  footerHalcyon: ["footerHalcyon"],
  footerBottomHalcyon: ["footerBottomHalcyon"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTermsOfService__ArgProps,
          internalVariantPropNames: PlasmicTermsOfService__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTermsOfService__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTermsOfService";
  } else {
    func.displayName = `PlasmicTermsOfService.${nodeName}`;
  }
  return func;
}

export const PlasmicTermsOfService = Object.assign(
  // Top-level PlasmicTermsOfService renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    halcyonNavBar: makeNodeComponent("halcyonNavBar"),
    bannerPolicies: makeNodeComponent("bannerPolicies"),
    section: makeNodeComponent("section"),
    containerTermsOfService: makeNodeComponent("containerTermsOfService"),
    footerHalcyon: makeNodeComponent("footerHalcyon"),
    footerBottomHalcyon: makeNodeComponent("footerBottomHalcyon"),
    // Metadata about props expected for PlasmicTermsOfService
    internalVariantProps: PlasmicTermsOfService__VariantProps,
    internalArgProps: PlasmicTermsOfService__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTermsOfService;
/* prettier-ignore-end */
